### ISSUE TITLE
Implement SMS & Email alerting to Vulncorr.py

### ISSUE THREAD

**Issue by gfunkoriginal** [gfunkoriginal/Threatelligence#6]
For the purpose of enhancing functionality, it would be beneficial to implement active alerting through either SMS and or Email . The contents of which would state to the recipient that x amount of MS patches are available from the latest published patch notification on "patch Tuesday".

**Comment by lewismc** [comment]
The code for this has been implemented within [intelnotification.py
](https://github.com/gfunkoriginal/Threatelligence/blob/master/threatelligence/cron/intelnotification.py)
