### ISSUE TITLE
Add a LIKE SQL statement into Vulncorr.py

### ISSUE THREAD

**Issue by gfunkoriginal** [gfunkoriginal/Threatelligence#8]
The current SQL statement within Vulncorr.py looks for exact matches with which to make correlations. This means that a lot of possibly eligble systems with which patches should be applied are being ignored as they do not exactly match the text variable being passed into the database by Vulncorr.py. 

There is a need then to amend the current SQL statement to carry out fuzzy searches for correlations.

**Comment by lewismc** [comment]
The SQL Statement referenced above can be found [vulncorr.py#L88-L96](https://github.com/gfunkoriginal/Threatelligence/blob/master/threatelligence/cron/vulncorr.py#L88-L96)

**Comment by lewismc** [comment]
I'll take a look and submit a PR

**Comment by lewismc** [comment]
@gfunkoriginal my suspicion is that the code should be changed to match

```
        result = cur.execute("SELECT * FROM database_servers WHERE InstalledApplications LIKE '%s' UNION ALL "
                         "SELECT * FROM email_servers WHERE InstalledApplications LIKE '%s' UNION ALL "
                         "SELECT * FROM dev_servers WHERE InstalledApplications LIKE '%s' UNION ALL "
                         "SELECT * FROM domain_controllers WHERE InstalledApplications LIKE '%s' UNION ALL "
                         "SELECT * FROM exchange WHERE InstalledApplications LIKE '%s' UNION ALL "
                         "SELECT * FROM file_transfer WHERE InstalledApplications LIKE '%s' UNION ALL "
                         "SELECT * FROM huxley WHERE InstalledApplications LIKE '%s' UNION ALL "
                         "SELECT * FROM pas WHERE InstalledApplications LIKE '%s'"
                         % (patch, patch, patch, patch, patch, patch, patch, patch))
```

Please copy the above syntax into your Python file.
Create a print statement somewhere such that you can view the results.
Remember you can set debug statements just after the execution and look into the values to see what is being returned.
Please write back here with any results.
Thanks

**Comment by gfunkoriginal** [comment]
Unfortunately this has not resolved the issue, the following errors wereprinted:

An error occurred whilst querying the asset database: near "Office": syntax error
An error occurred whilst querying the asset database: near "' UNION ALL SELECT \* FROM dev_servers WHERE InstalledApplications LIKE '": syntax error
An error occurred whilst querying the asset database: near "Edge": syntax error
An error occurred whilst querying the asset database: near "' UNION ALL SELECT \* FROM dev_servers WHERE InstalledApplications LIKE '": syntax error
An error occurred whilst querying the asset database: near "only": syntax error
An error occurred whilst querying the asset database: near "' UNION ALL SELECT \* FROM dev_servers WHERE InstalledApplications LIKE '": syntax error
An error occurred whilst querying the asset database: near "Explorer": syntax error
An error occurred whilst querying the asset database: near "' UNION ALL SELECT \* FROM dev_servers WHERE InstalledApplications LIKE '": syntax error
An error occurred whilst querying the asset database: near "Exchange": syntax error

**Comment by lewismc** [comment]
Please try the above now, there was a syntax error in one of the string substitutions.

**Comment by lewismc** [comment]
This is resolved as per new fuzzy matching in Vulncorr.py
